# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crypto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'crypto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63rypto.proto\x12\tcrypto.v1\"&\n\x14GetCryptoListRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\"z\n\tCryptoRow\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04last\x18\x02 \x01(\x01\x12\x12\n\npercentage\x18\x03 \x01(\x01\x12\x0e\n\x06volume\x18\x04 \x01(\x01\x12\x0c\n\x04high\x18\x05 \x01(\x01\x12\x0b\n\x03low\x18\x06 \x01(\x01\x12\x10\n\x08\x65xchange\x18\x07 \x01(\t\"@\n\x0b\x43ryptoError\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x85\x01\n\x15GetCryptoListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\"\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x14.crypto.v1.CryptoRow\x12&\n\x06\x65rrors\x18\x03 \x03(\x0b\x32\x16.crypto.v1.CryptoError\x12\x0f\n\x07partial\x18\x04 \x01(\x08\x32\x63\n\rCryptoService\x12R\n\rGetCryptoList\x12\x1f.crypto.v1.GetCryptoListRequest\x1a .crypto.v1.GetCryptoListResponseB+Z)crypto-api/internal/gen/cryptopb;cryptopbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crypto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)crypto-api/internal/gen/cryptopb;cryptopb'
  _globals['_GETCRYPTOLISTREQUEST']._serialized_start=27
  _globals['_GETCRYPTOLISTREQUEST']._serialized_end=65
  _globals['_CRYPTOROW']._serialized_start=67
  _globals['_CRYPTOROW']._serialized_end=189
  _globals['_CRYPTOERROR']._serialized_start=191
  _globals['_CRYPTOERROR']._serialized_end=255
  _globals['_GETCRYPTOLISTRESPONSE']._serialized_start=258
  _globals['_GETCRYPTOLISTRESPONSE']._serialized_end=391
  _globals['_CRYPTOSERVICE']._serialized_start=393
  _globals['_CRYPTOSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
